node-client-1:app2::memory=64
node-client-1:app3::memory=64:ports=aba,theo:xml=True
node-client-1:app4::memory=96:info="Big Bertha"
node-client-1:app5::memory=64
node-client-1:app6::memory=64
node-client-1:app7::memory=64
